services:
  catalog.db:
    image: mongo

  basket.db:
    image: redis

  discount.db:
    image: postgres

  ordering.db:
    image: mcr.microsoft.com/mssql/server

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile

  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  sqlserver_data: