services:
  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalog.db:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__ProductCollectionName=Products
      - DatabaseSettings__BrandCollectionName=Brands
      - DatabaseSettings__TypeCollectionName=Types
    depends_on:
      - catalog.db
    ports:
      - "8010:8080"
      - "8011:8081"
        

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basket.db:6379
    depends_on:
      - basket.db
    ports:
      - "8020:8080"
      - "8021:8081"